# Generated by Django 3.2.7 on 2021-10-10 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='T_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T_jobid', models.CharField(max_length=20, verbose_name='职工号')),
                ('T_name', models.CharField(max_length=10, verbose_name='姓名')),
                ('T_namePy', models.CharField(max_length=10, verbose_name='姓名拼音')),
                ('T_Sex', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=100, verbose_name='性别')),
                ('T_oldname', models.CharField(max_length=10, verbose_name='曾用名')),
                ('T_old', models.IntegerField(verbose_name='年龄')),
                ('T_Country', models.CharField(max_length=10, verbose_name='国家')),
                ('T_idnum', models.CharField(max_length=20, verbose_name='身份证号')),
                ('T_idtype', models.CharField(max_length=20, verbose_name='身份证件类型')),
                ('T_greenCard', models.CharField(choices=[('是', '是'), ('否', '否')], max_length=20, verbose_name='是否持有绿卡')),
                ('T_idlocal', models.CharField(max_length=30, verbose_name='户口所在地')),
                ('T_idfrom', models.CharField(max_length=30, verbose_name='籍贯')),
                ('T_idgroup', models.CharField(max_length=30, verbose_name='民族')),
                ('T_GAT', models.CharField(max_length=30, verbose_name='港澳台侨')),
                ('T_Wedding', models.CharField(choices=[('是', '是'), ('否', '否')], max_length=30, verbose_name='婚姻状态')),
                ('T_zfgroup', models.CharField(max_length=20, verbose_name='政治面貌')),
                ('T_birthday_confirm', models.DateTimeField(verbose_name='组织确认出生日期')),
                ('T_birthday', models.DateTimeField(verbose_name='出生日期')),
                ('T_workdate', models.DateTimeField(verbose_name='参加工作日期')),
                ('T_zfjoindate', models.DateTimeField(verbose_name='参加党派日期')),
                ('T_teacherType', models.CharField(max_length=20, verbose_name='教职工类别')),
                ('T_currentType', models.CharField(choices=[('是', '是'), ('否', '否')], max_length=20, verbose_name='当前状态（是否在职）')),
                ('T_fromSchool', models.CharField(max_length=20, verbose_name='所在学院')),
                ('T_fromClass', models.CharField(max_length=20, verbose_name='所在专业')),
                ('T_ttype', models.CharField(max_length=20, verbose_name='教师类型')),
                ('T_tfrom', models.CharField(max_length=20, verbose_name='教师来源')),
                ('T_InLiveAddress', models.TextField(max_length=1024, verbose_name='国内家庭住址')),
                ('T_QQ', models.CharField(max_length=10, verbose_name='QQ号')),
                ('T_WX', models.CharField(max_length=10, verbose_name='微信号')),
                ('T_InPhone', models.CharField(max_length=11, verbose_name='国内手机')),
                ('user_id', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
            options={
                'verbose_name': '教师信息',
                'verbose_name_plural': '教师信息',
                'db_table': 'T_info',
            },
        ),
        migrations.CreateModel(
            name='S_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_jobid', models.CharField(max_length=20, verbose_name='学号')),
                ('S_name', models.CharField(max_length=10, verbose_name='姓名')),
                ('S_namePy', models.CharField(max_length=10, verbose_name='姓名拼音')),
                ('S_Sex', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=100, verbose_name='性别')),
                ('S_oldname', models.CharField(max_length=10, verbose_name='曾用名')),
                ('S_old', models.IntegerField(verbose_name='年龄')),
                ('S_Country', models.CharField(max_length=10, verbose_name='国家')),
                ('S_idnum', models.CharField(max_length=20, verbose_name='身份证号')),
                ('S_idtype', models.CharField(max_length=20, verbose_name='身份证件类型')),
                ('S_greenCard', models.CharField(choices=[('是', '是'), ('否', '否')], max_length=20, verbose_name='是否持有绿卡')),
                ('S_idlocal', models.CharField(max_length=30, verbose_name='户口所在地')),
                ('S_idfrom', models.CharField(max_length=30, verbose_name='籍贯')),
                ('S_idgroup', models.CharField(max_length=30, verbose_name='民族')),
                ('S_GAT', models.CharField(max_length=30, verbose_name='港澳台侨')),
                ('S_Wedding', models.CharField(choices=[('是', '是'), ('否', '否')], max_length=30, verbose_name='婚姻状态')),
                ('S_zfgroup', models.CharField(max_length=20, verbose_name='政治面貌')),
                ('S_birthday_confirm', models.DateTimeField(verbose_name='组织确认出生日期')),
                ('S_birthday', models.DateTimeField(verbose_name='出生日期')),
                ('S_workdate', models.DateTimeField(verbose_name='入学日期')),
                ('S_fromSchool', models.CharField(max_length=20, verbose_name='所在学院')),
                ('S_fromClass', models.CharField(max_length=20, verbose_name='专业')),
                ('S_InLiveAddress', models.TextField(max_length=1024, verbose_name='国内家庭住址')),
                ('S_QQ', models.CharField(max_length=10, verbose_name='QQ号')),
                ('S_WX', models.CharField(max_length=10, verbose_name='微信号')),
                ('S_InPhone', models.CharField(max_length=11, verbose_name='国内手机')),
                ('user_id', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
            options={
                'verbose_name': '学生信息',
                'verbose_name_plural': '学生信息',
                'db_table': 'S_info',
            },
        ),
        migrations.CreateModel(
            name='outCheckin',
            fields=[
                ('C_id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('C_group', models.CharField(blank=True, choices=[('教师', '教师'), ('学生', '学生')], max_length=135, verbose_name='身份')),
                ('C_ToCountry', models.CharField(max_length=250, verbose_name='去往外方学校')),
                ('C_ToTime', models.DateTimeField(verbose_name='出国机票时间')),
                ('C_ArrTime', models.DateTimeField(blank=True, null=True, verbose_name='回国抵达海关时间')),
                ('C_ToMajor', models.CharField(max_length=30, verbose_name='国外学习专业')),
                ('C_JoinProject', models.CharField(max_length=1024, verbose_name='参加项目')),
                ('C_OutPhone', models.CharField(max_length=15, verbose_name='国外手机')),
                ('C_EName', models.CharField(max_length=15, verbose_name='紧急联系人姓名')),
                ('C_EPhone', models.CharField(max_length=15, verbose_name='紧急联系人手机号')),
                ('C_Face', models.CharField(max_length=15, verbose_name='政治面貌')),
                ('C_Other', models.CharField(max_length=1024, verbose_name='其他（是否在国内读网课）')),
                ('user_id', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
            options={
                'verbose_name': '出国信息',
                'verbose_name_plural': '出国信息',
                'db_table': 'C_Things',
            },
        ),
    ]
