# Generated by Django 3.2.7 on 2021-10-05 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='T_info',
            fields=[
                ('T_id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('T_jobid', models.CharField(max_length=20, verbose_name='职工号')),
                ('T_name', models.CharField(max_length=10, verbose_name='姓名')),
                ('T_namePy', models.CharField(max_length=10, verbose_name='姓名拼音')),
                ('T_Sex', models.CharField(choices=[('M', '男'), ('W', '女')], max_length=100, verbose_name='性别')),
                ('T_oldname', models.CharField(max_length=10, verbose_name='曾用名')),
                ('T_old', models.IntegerField(verbose_name='年龄')),
                ('T_Country', models.CharField(max_length=10, verbose_name='国家')),
                ('T_idnum', models.CharField(max_length=20, verbose_name='身份证号')),
                ('T_idtype', models.CharField(max_length=20, verbose_name='身份证件类型')),
                ('T_greenCard', models.CharField(choices=[('Y', '是'), ('N', '否')], max_length=20, verbose_name='是否持有绿卡')),
                ('T_idlocal', models.CharField(max_length=30, verbose_name='户口所在地')),
                ('T_idfrom', models.CharField(max_length=30, verbose_name='籍贯')),
                ('T_idgroup', models.CharField(max_length=30, verbose_name='民族')),
                ('T_GAT', models.CharField(max_length=30, verbose_name='港澳台侨')),
                ('T_Wedding', models.CharField(choices=[('Y', '是'), ('N', '否')], max_length=30, verbose_name='婚姻状态')),
                ('T_zfgroup', models.CharField(max_length=20, verbose_name='政治面貌')),
                ('T_birthday_confirm', models.DateTimeField(verbose_name='组织确认出生日期')),
                ('T_birthday', models.DateTimeField(verbose_name='出生日期')),
                ('T_workdate', models.DateTimeField(verbose_name='参加工作日期')),
                ('T_zfjoindate', models.DateTimeField(verbose_name='参加党派日期')),
                ('T_teacherType', models.CharField(max_length=20, verbose_name='教职工类别')),
                ('T_currentType', models.CharField(choices=[('Y', '是'), ('N', '否')], max_length=20, verbose_name='当前状态（是否在职）')),
                ('T_fromSchool', models.CharField(max_length=20, verbose_name='所在单位')),
                ('T_fromClass', models.CharField(max_length=20, verbose_name='所在教研室')),
                ('T_ttype', models.CharField(max_length=20, verbose_name='教师类型')),
                ('T_tfrom', models.CharField(max_length=20, verbose_name='教师来源')),
                ('user_id', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
            options={
                'verbose_name': '教师信息',
                'verbose_name_plural': '教师信息',
                'db_table': 'T_info',
            },
        ),
        migrations.CreateModel(
            name='outCheckin',
            fields=[
                ('C_id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('C_name', models.CharField(max_length=10, verbose_name='姓名')),
                ('C_group', models.CharField(blank=True, choices=[('T', '教师'), ('S', '学生')], max_length=135, verbose_name='身份')),
                ('C_School', models.CharField(max_length=20, verbose_name='学院')),
                ('C_idCardNum', models.CharField(max_length=18, verbose_name='身份证号')),
                ('C_Sex', models.CharField(choices=[('M', '男'), ('W', '女')], max_length=100, verbose_name='性别')),
                ('C_idWorkNum', models.CharField(max_length=20, verbose_name='学号')),
                ('C_major', models.CharField(max_length=30, verbose_name='专业')),
                ('C_ToCountry', models.CharField(max_length=250, verbose_name='去往外方学校')),
                ('C_ToTime', models.DateTimeField(verbose_name='出国机票时间')),
                ('C_ArrTime', models.DateTimeField(blank=True, null=True, verbose_name='回国抵达海关时间')),
                ('C_ToMajor', models.CharField(max_length=30, verbose_name='国外学习专业')),
                ('C_InLiveAddress', models.TextField(max_length=1024, verbose_name='国内家庭住址')),
                ('C_JoinProject', models.CharField(max_length=1024, verbose_name='参加项目')),
                ('C_InPhone', models.CharField(max_length=11, verbose_name='国内手机')),
                ('C_OutPhone', models.CharField(max_length=15, verbose_name='国外手机')),
                ('C_QQ', models.CharField(max_length=10, verbose_name='QQ号')),
                ('C_WX', models.CharField(max_length=10, verbose_name='微信号')),
                ('C_EName', models.CharField(max_length=15, verbose_name='紧急联系人姓名')),
                ('C_EPhone', models.CharField(max_length=15, verbose_name='紧急联系人手机号')),
                ('C_Face', models.CharField(max_length=15, verbose_name='政治面貌')),
                ('C_Other', models.CharField(max_length=1024, verbose_name='其他（是否在国内读网课）')),
                ('user_id', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
            options={
                'verbose_name': '出国信息',
                'verbose_name_plural': '出国信息',
                'db_table': 'C_Things',
            },
        ),
    ]
