# Generated by Django 3.2.7 on 2021-10-05 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('outPeople', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='S_info',
            fields=[
                ('S_id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('S_jobid', models.CharField(max_length=20, verbose_name='学号')),
                ('S_name', models.CharField(max_length=10, verbose_name='姓名')),
                ('S_namePy', models.CharField(max_length=10, verbose_name='姓名拼音')),
                ('S_Sex', models.CharField(choices=[('M', '男'), ('W', '女')], max_length=100, verbose_name='性别')),
                ('S_oldname', models.CharField(max_length=10, verbose_name='曾用名')),
                ('S_old', models.IntegerField(verbose_name='年龄')),
                ('S_Country', models.CharField(max_length=10, verbose_name='国家')),
                ('S_idnum', models.CharField(max_length=20, verbose_name='身份证号')),
                ('S_idtype', models.CharField(max_length=20, verbose_name='身份证件类型')),
                ('S_greenCard', models.CharField(choices=[('Y', '是'), ('N', '否')], max_length=20, verbose_name='是否持有绿卡')),
                ('S_idlocal', models.CharField(max_length=30, verbose_name='户口所在地')),
                ('S_idfrom', models.CharField(max_length=30, verbose_name='籍贯')),
                ('S_idgroup', models.CharField(max_length=30, verbose_name='民族')),
                ('S_GAT', models.CharField(max_length=30, verbose_name='港澳台侨')),
                ('S_Wedding', models.CharField(choices=[('Y', '是'), ('N', '否')], max_length=30, verbose_name='婚姻状态')),
                ('S_zfgroup', models.CharField(max_length=20, verbose_name='政治面貌')),
                ('S_birthday_confirm', models.DateTimeField(verbose_name='组织确认出生日期')),
                ('S_birthday', models.DateTimeField(verbose_name='出生日期')),
                ('S_workdate', models.DateTimeField(verbose_name='入学日期')),
                ('S_fromSchool', models.CharField(max_length=20, verbose_name='所在学院')),
                ('S_fromClass', models.CharField(max_length=20, verbose_name='专业')),
                ('user_id', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
            options={
                'verbose_name': '学生信息',
                'verbose_name_plural': '学生信息',
                'db_table': 'S_info',
            },
        ),
    ]
