# Generated by Django 3.2.7 on 2021-10-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outPeople', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='s_info',
            name='Test',
            field=models.CharField(default=1, max_length=11, verbose_name='测试'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_info',
            name='Test',
            field=models.CharField(default=1, max_length=11, verbose_name='测试'),
            preserve_default=False,
        ),
    ]
