# Generated by Django 3.2.7 on 2021-09-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outPeople', '0002_alter_studentinformation_s_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinformation',
            name='S_Sex',
            field=models.CharField(choices=[('M', '男'), ('W', '女')], max_length=100, verbose_name='性别'),
        ),
    ]
