# Generated by Django 3.1.14 on 2021-12-13 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('outpeopleCheckin', '0002_tinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=135, verbose_name='姓名')),
                ('S_jobid', models.CharField(max_length=20, verbose_name='学号')),
                ('S_name', models.CharField(max_length=10, verbose_name='姓名')),
                ('S_namePy', models.CharField(max_length=10, verbose_name='姓名拼音')),
                ('S_Sex', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=100, verbose_name='性别')),
                ('S_oldname', models.CharField(max_length=10, verbose_name='曾用名')),
                ('S_old', models.IntegerField(verbose_name='年龄')),
                ('S_Country', models.CharField(max_length=10, verbose_name='国家')),
                ('S_idnum', models.CharField(max_length=20, verbose_name='身份证号')),
                ('S_idtype', models.CharField(max_length=20, verbose_name='身份证件类型')),
                ('S_greenCard', models.CharField(choices=[('是', '是'), ('否', '否')], max_length=20, verbose_name='是否持有绿卡')),
                ('S_idlocal', models.CharField(max_length=30, verbose_name='户口所在地')),
                ('S_idfrom', models.CharField(max_length=30, verbose_name='籍贯')),
                ('S_idgroup', models.CharField(max_length=30, verbose_name='民族')),
                ('S_GAT', models.CharField(max_length=30, verbose_name='港澳台侨')),
                ('S_Wedding', models.CharField(choices=[('是', '是'), ('否', '否')], max_length=30, verbose_name='婚姻状态')),
                ('S_zfgroup', models.CharField(max_length=20, verbose_name='政治面貌')),
                ('S_birthday_confirm', models.DateTimeField(verbose_name='组织确认出生日期')),
                ('S_birthday', models.DateTimeField(verbose_name='出生日期')),
                ('S_workdate', models.DateTimeField(verbose_name='入学日期')),
                ('S_fromSchool', models.CharField(max_length=20, verbose_name='所在学院')),
                ('S_fromClass', models.CharField(max_length=20, verbose_name='专业')),
                ('S_InLiveAddress', models.TextField(max_length=1024, verbose_name='国内家庭住址')),
                ('S_QQ', models.CharField(max_length=10, verbose_name='QQ号')),
                ('S_WX', models.CharField(max_length=10, verbose_name='微信号')),
                ('S_InPhone', models.CharField(max_length=11, verbose_name='国内手机')),
                ('Test', models.CharField(max_length=11, verbose_name='测试')),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
            options={
                'verbose_name': '学生信息',
                'verbose_name_plural': '学生信息列表',
            },
        ),
    ]
