# Generated by Django 3.1.14 on 2021-12-13 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outpeopleCheckin', '0005_auto_20211213_1934'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cinfo',
            table=None,
        ),
    ]
