# Generated by Django 3.1.14 on 2021-12-14 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outpeopleCheckin', '0006_auto_20211213_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sinfo',
            name='username',
        ),
    ]
