# Generated by Django 3.1.14 on 2021-12-14 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('outpeopleCheckin', '0007_remove_sinfo_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinfo',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, unique=True, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='tinfo',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, unique=True, verbose_name='用户名'),
        ),
    ]
