# Generated by Django 3.1.14 on 2021-12-14 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outpeopleCheckin', '0008_auto_20211214_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinfo',
            name='S_name',
            field=models.ManyToManyField(blank=True, to='outpeopleCheckin.Sinfo', verbose_name='学生姓名'),
        ),
        migrations.AddField(
            model_name='cinfo',
            name='T_name',
            field=models.ManyToManyField(blank=True, to='outpeopleCheckin.Tinfo', verbose_name='教师姓名'),
        ),
    ]
