# Generated by Django 3.1.14 on 2021-12-14 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outpeopleCheckin', '0010_auto_20211214_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinfo',
            name='S_name',
        ),
        migrations.RemoveField(
            model_name='cinfo',
            name='T_name',
        ),
    ]
