# Generated by Django 3.1.14 on 2021-12-14 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outpeopleCheckin', '0011_auto_20211214_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinfo',
            name='S_name',
            field=models.ForeignKey(blank=True, default=111, on_delete=django.db.models.deletion.CASCADE, to='outpeopleCheckin.sinfo', verbose_name='学生姓名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cinfo',
            name='T_name',
            field=models.ForeignKey(blank=True, default=111, on_delete=django.db.models.deletion.CASCADE, to='outpeopleCheckin.tinfo', verbose_name='教师姓名'),
            preserve_default=False,
        ),
    ]
