# Generated by Django 3.1.14 on 2021-12-14 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('outpeopleCheckin', '0012_auto_20211214_1048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cinfo',
            options={'verbose_name': '教师出国信息', 'verbose_name_plural': '教师出国信息列表'},
        ),
        migrations.RemoveField(
            model_name='cinfo',
            name='S_name',
        ),
        migrations.CreateModel(
            name='SCinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_group', models.CharField(blank=True, choices=[('教师', '教师'), ('学生', '学生')], max_length=135, verbose_name='身份')),
                ('C_ToCountry', models.CharField(max_length=250, verbose_name='去往外方学校')),
                ('C_ToTime', models.DateTimeField(verbose_name='出国机票时间')),
                ('C_ArrTime', models.DateTimeField(blank=True, null=True, verbose_name='回国抵达海关时间')),
                ('C_ToMajor', models.CharField(max_length=30, verbose_name='国外学习专业')),
                ('C_JoinProject', models.CharField(max_length=1024, verbose_name='参加项目')),
                ('C_OutPhone', models.CharField(max_length=15, verbose_name='国外手机')),
                ('C_EName', models.CharField(max_length=15, verbose_name='紧急联系人姓名')),
                ('C_EPhone', models.CharField(max_length=15, verbose_name='紧急联系人手机号')),
                ('C_Other', models.CharField(max_length=1024, verbose_name='其他（是否在国内读网课）')),
                ('S_name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='outpeopleCheckin.sinfo', verbose_name='学生姓名')),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户名')),
            ],
            options={
                'verbose_name': '学生出国信息',
                'verbose_name_plural': '学生出国信息列表',
            },
        ),
    ]
