# Generated by Django 3.1.14 on 2021-12-14 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outpeopleCheckin', '0013_auto_20211214_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cinfo',
            old_name='T_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='scinfo',
            old_name='S_name',
            new_name='name',
        ),
    ]
