# Generated by Django 3.1.3 on 2021-04-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CheckIn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinformation',
            name='S_EName',
            field=models.CharField(max_length=15, verbose_name='紧急联系人姓名'),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='S_EPhone',
            field=models.CharField(max_length=15, verbose_name='紧急联系人手机号'),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='S_Face',
            field=models.CharField(max_length=15, verbose_name='政治面貌'),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='S_IdCardNum',
            field=models.CharField(max_length=18, verbose_name='身份证号'),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='S_IdWorkNum',
            field=models.CharField(max_length=20, verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='S_InPhone',
            field=models.CharField(max_length=11, verbose_name='国内手机'),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='S_JoinProject',
            field=models.CharField(max_length=1024, verbose_name='参加项目'),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='S_Other',
            field=models.CharField(max_length=1024, verbose_name='其他（是否在国内读网课）'),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='S_OutPhone',
            field=models.CharField(max_length=15, verbose_name='国外手机'),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='S_QQ',
            field=models.CharField(max_length=10, verbose_name='QQ号'),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='S_ToCountry',
            field=models.CharField(max_length=250, verbose_name='去往外方学校'),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='S_ToMajor',
            field=models.CharField(max_length=30, verbose_name='国外学习专业'),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='S_WX',
            field=models.CharField(max_length=10, verbose_name='微信号'),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='S_major',
            field=models.CharField(max_length=30, verbose_name='专业'),
        ),
        migrations.AlterField(
            model_name='teacherinformation',
            name='T_EName',
            field=models.CharField(max_length=15, verbose_name='紧急联系人姓名'),
        ),
        migrations.AlterField(
            model_name='teacherinformation',
            name='T_EPhone',
            field=models.CharField(max_length=15, verbose_name='紧急联系人手机号'),
        ),
        migrations.AlterField(
            model_name='teacherinformation',
            name='T_Face',
            field=models.CharField(max_length=15, verbose_name='政治面貌'),
        ),
        migrations.AlterField(
            model_name='teacherinformation',
            name='T_IdCardNum',
            field=models.CharField(max_length=18, verbose_name='身份证号'),
        ),
        migrations.AlterField(
            model_name='teacherinformation',
            name='T_IdWorkNum',
            field=models.CharField(max_length=20, verbose_name='职工号'),
        ),
        migrations.AlterField(
            model_name='teacherinformation',
            name='T_InPhone',
            field=models.CharField(max_length=11, verbose_name='国内手机'),
        ),
        migrations.AlterField(
            model_name='teacherinformation',
            name='T_JoinProject',
            field=models.CharField(max_length=1024, verbose_name='参加项目'),
        ),
        migrations.AlterField(
            model_name='teacherinformation',
            name='T_Other',
            field=models.CharField(max_length=1024, verbose_name='其他（是否在国内读网课）'),
        ),
        migrations.AlterField(
            model_name='teacherinformation',
            name='T_OutPhone',
            field=models.CharField(max_length=15, verbose_name='国外手机'),
        ),
        migrations.AlterField(
            model_name='teacherinformation',
            name='T_QQ',
            field=models.CharField(max_length=10, verbose_name='QQ号'),
        ),
        migrations.AlterField(
            model_name='teacherinformation',
            name='T_School',
            field=models.CharField(max_length=30, verbose_name='学院\\部门'),
        ),
        migrations.AlterField(
            model_name='teacherinformation',
            name='T_ToCountry',
            field=models.CharField(max_length=250, verbose_name='去往外方学校'),
        ),
        migrations.AlterField(
            model_name='teacherinformation',
            name='T_ToMajor',
            field=models.CharField(max_length=30, verbose_name='国外学习专业'),
        ),
        migrations.AlterField(
            model_name='teacherinformation',
            name='T_WX',
            field=models.CharField(max_length=10, verbose_name='微信号'),
        ),
        migrations.AlterField(
            model_name='teacherinformation',
            name='T_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='序号'),
        ),
        migrations.AlterField(
            model_name='teacherinformation',
            name='T_major',
            field=models.CharField(max_length=30, verbose_name='专业'),
        ),
    ]
