# Generated by Django 3.1.3 on 2021-04-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CheckIn', '0002_auto_20210425_1815'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentinformation',
            options={'verbose_name': '学生信息', 'verbose_name_plural': '学生信息'},
        ),
        migrations.AlterModelOptions(
            name='teacherinformation',
            options={'verbose_name': '教师信息', 'verbose_name_plural': '教师信息'},
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='S_ArrTime',
            field=models.DateTimeField(blank=True, verbose_name='回国抵达海关时间'),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='S_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='序号'),
        ),
        migrations.AlterField(
            model_name='teacherinformation',
            name='T_ArrTime',
            field=models.DateTimeField(blank=True, verbose_name='回国抵达海关时间'),
        ),
    ]
