# Generated by Django 3.1.3 on 2021-04-25 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CheckIn', '0004_auto_20210425_1933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentinformation',
            old_name='applicant',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='teacherinformation',
            old_name='applicant',
            new_name='user_id',
        ),
    ]
