# Generated by Django 3.1.3 on 2021-04-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CheckIn', '0006_auto_20210425_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinformation',
            name='S_ArrTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='回国抵达海关时间'),
        ),
    ]
