# Generated by Django 3.1.3 on 2021-04-26 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CheckIn', '0007_auto_20210425_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherinformation',
            name='T_group',
            field=models.CharField(blank=True, choices=[(0, '教师'), (1, '学生')], max_length=135, verbose_name='身份'),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='user_id',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='申请人'),
        ),
        migrations.AlterField(
            model_name='teacherinformation',
            name='user_id',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='申请人'),
        ),
    ]
