# Generated by Django 3.1.4 on 2021-05-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CheckIn', '0009_auto_20210426_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinformation',
            name='S_group',
            field=models.CharField(blank=True, choices=[('T', '教师'), ('S', '学生')], max_length=135, verbose_name='身份'),
        ),
        migrations.AlterField(
            model_name='teacherinformation',
            name='T_group',
            field=models.CharField(blank=True, choices=[('T', '教师'), ('S', '学生')], max_length=135, verbose_name='身份'),
        ),
    ]
