# Generated by Django 3.1.4 on 2021-05-17 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CheckIn', '0010_auto_20210517_1429'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherInformation',
        ),
    ]
